### ISSUE TITLE
Ingest might not start correctly after server reboot 

### ISSUE THREAD

**Issue by sillevl** [vives-dust/framework#177]
After a server reboot, data is dropped by bug in ingest. The ingest service shows the following error in the logs:

```
ingest_1  | Redis error:  Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
ingest_1  |     at doWrite (_stream_writable.js:399:19)
ingest_1  |     at writeOrBuffer (_stream_writable.js:387:5)
ingest_1  |     at Socket.Writable.write (_stream_writable.js:318:11)
ingest_1  |     at /usr/src/app/node_modules/tedis/build/core/base.js:83:26
ingest_1  |     at new Promise (<anonymous>)
ingest_1  |     at Tedis.Base.command (/usr/src/app/node_modules/tedis/build/core/base.js:78:16)
ingest_1  |     at Tedis.RedisList.rpush (/usr/src/app/node_modules/tedis/build/api/list.js:111:29)
ingest_1  |     at RedisClient.<anonymous> (/usr/src/app/dist/RedisClient.js:65:61)
ingest_1  |     at step (/usr/src/app/dist/RedisClient.js:33:23)
ingest_1  |     at Object.next (/usr/src/app/dist/RedisClient.js:14:53) {
ingest_1  |   code: 'ERR_STREAM_DESTROYED'
ingest_1  | }
```

further investigation is needed. MUST be solved !

**Comment by sillevl** [comment]
hopefully resolved in 822e712
